version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: globals
    versions:
    - 13.5.0
    - 13.6.0
    - 13.7.0
  - dependency-name: fsevents
    versions:
    - 2.3.1
  - dependency-name: glob-parent
    versions:
    - 5.1.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: has-flag
    versions:
    - 4.0.0
